name: Check for updates
on:
  schedule: # for scheduling to work this file must be in the default branch
  - cron: "0 * * * *" # run every hour
  workflow_dispatch: # can be manually dispatched under GitHub's "Actions" tab

jobs:
  flatpak-external-data-checker:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        branch: [ master ] # list all branches to check

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ matrix.branch }}

      - uses: docker://ghcr.io/flathub/flatpak-external-data-checker:latest
        env:
          GIT_AUTHOR_NAME: Flatpak External Data Checker
          GIT_COMMITTER_NAME: Flatpak External Data Checker
          # email sets "github-actions[bot]" as commit author, see https://github.community/t/github-actions-bot-email-address/17204/6
          GIT_AUTHOR_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
          GIT_COMMITTER_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: --commit-only --never-fork com.apifox.Apifox.yaml

      - run: curl -o apifox.zip https://file-assets.apifox.com/download/Apifox-linux-deb-latest.zip
      - run: unzip apifox.zip
      - run: ar -x *.deb
      - run: tar -xJf data.tar.xz
      - run: gunzip -d usr/share/doc/apifox/changelog.gz

      - name: update metainfo
        run: |
          set -x

          pwd

          ls -l

          echo GITHUB_WORKSPACE=$GITHUB_WORKSPACE
          cd $GITHUB_WORKSPACE

          APIFOX_LAST_VERSION=`head -n 1 usr/share/doc/apifox/changelog | tr -d '()' | cut -d ' ' -f 2`

          grep -q "$APIFOX_LAST_VERSION" com.apifox.Apifox.metainfo.xml
          [ $? -eq 0 ] && exit 0

          curl -o changelog https://docs.apifox.com/changelog
          RELEASE_DATE=$(grep -F $APIFOX_LAST_VERSION -C 2 changelog | tail -n 1 | tr -d '`')

          cat > release.txt  << EOF
            <release version="$APIFOX_LAST_VERSION" date="$RELEASE_DATE">
              <url>https://docs.apifox.com/changelog</url>
            </release>
          EOF

          sed '/<releases>/rrelease.txt' com.apifox.Apifox.metainfo.xml

          git add com.apifox.Apifox.metainfo.xml
          git commit -m 'Update the version in the metadata'
          git push
